# Generated by Django 4.2.4 on 2023-10-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism_app', '0002_alter_queries_date_of_travel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='children',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='infants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queries',
            name='flight',
            field=models.CharField(choices=[('One-way', 'Flight Option 1'), ('Round-trip', 'Flight Option 2')], default='one-way', max_length=20),
        ),
    ]
